language: node_js
node_js:
- '0.10'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update -qq
before_script:
- npm install -g karma karma-cli
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: GI4p5+HpcPWAX5G1z8PL9Zp9gSgTfdkadd4bNy1d6LA2CKiYZMXx8fbjAp41qIU7RC2mQ07rxz7/6u7zFtP0tvH3iOYxuD5BvPUX2txzezuIibhJrD89RUIEHFpnVkt4nk7fF8WwpaGgx/3QJrpWAR/ImRA4Xg0jUG6eb1GUd7g=
  app: pongjs
  on:
    repo: enricolucia/pong
